export interface CompReport {
  id?: number;
  user_id: string;
  meet: string;
  selected_meet_type: string;
  meet_date: string;
  bodyweight: string;
  performance_rating: number;
  physical_preparedness_rating: number;
  mental_preparedness_rating: number;
  nutrition: string;
  hydration: string;
  did_well: string;
  needs_work: string;
  good_from_training: string;
  cues: string;
  focus: string;
  satisfaction: number;
  confidence: number;
  pressure_handling: number;
  what_learned: string;
  what_proud_of: string;
  snatch1?: string | null;
  snatch2?: string | null;
  snatch3?: string | null;
  cj1?: string | null;
  cj2?: string | null;
  cj3?: string | null;
  snatch_best?: number | null;
  cj_best?: number | null;
  squat1?: string | null;
  squat2?: string | null;
  squat3?: string | null;
  bench1?: string | null;
  bench2?: string | null;
  bench3?: string | null;
  deadlift1?: string | null;
  deadlift2?: string | null;
  deadlift3?: string | null;
  squat_best?: number | null;
  bench_best?: number | null;
  deadlift_best?: number | null;
  created_at: string;
}
